In [ ]:
!python -m pip install -U python-woc pandas matplotlib

In [2]:
from woc.remote import WocMapsRemote
from tqdm import tqdm
import pandas as pd
# creates the client
woc = WocMapsRemote( base_url="https://worldofcode.org/api/")
# if you got an API key
# woc = WocMapsRemote( base_url="https://worldofcode.org/api/", api_key="woc-XXXXXX-YYYYYY" )

# Now for each of the ten projects you were assigned get commits, e.g.
projects = [
    'microsoft/TextWorld',
    'microsoft/unilm',
    'ExaScience/macau',
    'keras-team/autokeras',
    'cgentemann/cloud_science',
    'gauzias/slam',
    'Ivanlh20/multem',
    'slundberg/shap',
    'MITgcm/MITgcm',
    'MrGiovanni/ModelsGenesis'
]
list_df_commits = []
for prj in projects:
  # Convert GitHub repository names to WoC V2412 project names
  prj = prj.lower().replace('/','_',2)
  commits = woc.get_values('p2c', prj)
  df = pd.DataFrame(commits, columns=["sha1"])
  df['project'] = prj
  list_df_commits.append(df)
df = pd.concat(list_df_commits)
#perhaps save the list (if no errors) so you do not need to retrieve them again
df.to_csv('df_commits.csv')
df.head(1)

                                       sha1              project
0  00011bd91daf73b71f1278d52a35424b176a8807  microsoft_textworld

In [5]:
# If the number of commits its not very large, you can try to get them all at the same time,
# The max batch size is 10
import time
# let us first split df['sha1'] in chunks
chunks = [df['sha1'][x:x+10] for x in range(0, len(df), 10)]
commit_data = []

for chunk in tqdm(chunks): # iterate over the commits
  # res, err = woc.show_content_many('commit',chunk.to_list())

  # commit.tch returns the same data but faster
  res, err = woc.get_values_many('commit.tch',chunk.to_list())
  res = {k: v[0] for k, v in res.items()}  # this conversion is necessary because of the internal implementation

  # to walk around the rate limit
  time.sleep(1)

  if err: # check for errors
    print('Got Errors', err)

  for commit_sha, commit in res.items():
    # flatten commit objects
    commit_data.append({
          'commit': commit_sha,
          'tree': commit[0],
          'parent': list(commit[1]),
          'author': commit[2][0],
          'author_time': int(commit[2][1]),
          'author_tz': commit[2][2],
          'committer': commit[3][0],
          'committer_time': int(commit[3][1]),
          'committer_tz': commit[3][2],
          'message': commit[4],
    })

df_commit_data = pd.DataFrame(commit_data)
df_commit_data = df_commit_data.merge(df, left_on='commit', right_on='sha1')
df_commit_data.to_csv('df_commit_data.csv', index=False)
df_commit_data.head(2)

  0%|▏                                                                                                                                                                                                          | 5/4682 [00:05<1:19:31,  1.02s/it]

Got Errors {'09119a40fb6362614aade31732bed8b8d15eefff': 'Key 09119a40fb6362614aade31732bed8b8d15eefff not found in /da5_fast/All.sha1c/commit_9.tch', '09bfc8e053b6c2ccf28597e6c6872c6cb45fa31c': 'Key 09bfc8e053b6c2ccf28597e6c6872c6cb45fa31c not found in /da5_fast/All.sha1c/commit_9.tch'}

  0%|▎                                                                                                                                                                                                          | 8/4682 [00:08<1:19:43,  1.02s/it]

Got Errors {'1272d4baddca7f942e61341c02762ba013265e26': 'Key 1272d4baddca7f942e61341c02762ba013265e26 not found in /da5_fast/All.sha1c/commit_18.tch'}

  0%|▍                                                                                                                                                                                                         | 10/4682 [00:10<1:19:32,  1.02s/it]

Got Errors {'15e0f00016b0f6394b674ab34e31646885f9bb51': 'Key 15e0f00016b0f6394b674ab34e31646885f9bb51 not found in /da5_fast/All.sha1c/commit_21.tch'}

  1%|█▊                                                                                                                                                                                                        | 43/4682 [00:43<1:19:01,  1.02s/it]

Got Errors {'7381d465e7a2504640fa49015835fb72301668fa': 'Key 7381d465e7a2504640fa49015835fb72301668fa not found in /da5_fast/All.sha1c/commit_115.tch'}

  1%|██▊                                                                                                                                                                                                       | 64/4682 [01:05<1:18:43,  1.02s/it]

Got Errors {'a52c77fb844b819246e5d68371878cf591ca69bd': 'Key a52c77fb844b819246e5d68371878cf591ca69bd not found in /da5_fast/All.sha1c/commit_37.tch'}

  1%|██▉                                                                                                                                                                                                       | 69/4682 [01:10<1:18:30,  1.02s/it]

Got Errors {'bb51e0f320b3b5207d657781587bd7a09c8e4e51': 'Key bb51e0f320b3b5207d657781587bd7a09c8e4e51 not found in /da5_fast/All.sha1c/commit_59.tch'}

  2%|███▉                                                                                                                                                                                                      | 91/4682 [01:33<1:18:01,  1.02s/it]

Got Errors {'f77f76716987794c46a76b3653c0e63fe0d1a5f9': 'Key f77f76716987794c46a76b3653c0e63fe0d1a5f9 not found in /da5_fast/All.sha1c/commit_119.tch'}

  5%|██████████▉                                                                                                                                                                                              | 254/4682 [04:19<1:15:31,  1.02s/it]

Got Errors {'0147bf43791768585caacf6ccc5b298712656b34': 'Key 0147bf43791768585caacf6ccc5b298712656b34 not found in /da5_fast/All.sha1c/commit_1.tch'}

  6%|███████████▏                                                                                                                                                                                             | 260/4682 [04:25<1:15:08,  1.02s/it]

Got Errors {'05a723baa9634e6626c5423b29b6df336756dd54': 'Key 05a723baa9634e6626c5423b29b6df336756dd54 not found in /da5_fast/All.sha1c/commit_5.tch'}

  6%|████████████▊                                                                                                                                                                                            | 297/4682 [05:03<1:14:40,  1.02s/it]

Got Errors {'1db07e346ba151e07f8bceace7b219bc4ec3a440': 'Key 1db07e346ba151e07f8bceace7b219bc4ec3a440 not found in /da5_fast/All.sha1c/commit_29.tch'}

  7%|█████████████▊                                                                                                                                                                                           | 323/4682 [05:30<1:14:36,  1.03s/it]

Got Errors {'2dd3001179af91795b175e234897922003acd9b6': 'Key 2dd3001179af91795b175e234897922003acd9b6 not found in /da5_fast/All.sha1c/commit_45.tch'}

  7%|██████████████▎                                                                                                                                                                                          | 333/4682 [05:40<1:14:30,  1.03s/it]

Got Errors {'330c4f7d8aa7f84cab7d869e763357a14b171f8e': 'Key 330c4f7d8aa7f84cab7d869e763357a14b171f8e not found in /da5_fast/All.sha1c/commit_51.tch'}

  7%|██████████████▊                                                                                                                                                                                          | 344/4682 [05:51<1:13:50,  1.02s/it]

Got Errors {'3918a3bc29b6b24d0b42c04d8d22d64216559b81': 'Key 3918a3bc29b6b24d0b42c04d8d22d64216559b81 not found in /da5_fast/All.sha1c/commit_57.tch'}

  7%|██████████████▊                                                                                                                                                                                          | 345/4682 [05:52<1:13:49,  1.02s/it]

Got Errors {'39a8c6a73802cc8ab66ca41fda0ee6c5cfef75b1': 'Key 39a8c6a73802cc8ab66ca41fda0ee6c5cfef75b1 not found in /da5_fast/All.sha1c/commit_57.tch'}

  7%|██████████████▉                                                                                                                                                                                          | 348/4682 [05:55<1:13:40,  1.02s/it]

Got Errors {'3b303296b34c09b9e067ad61e78fcfc931190c5c': 'Key 3b303296b34c09b9e067ad61e78fcfc931190c5c not found in /da5_fast/All.sha1c/commit_59.tch'}

  7%|██████████████▉                                                                                                                                                                                          | 349/4682 [05:56<1:13:39,  1.02s/it]

Got Errors {'3bcb2e4b7e9028c24a0363d988ac482fcc28a0e6': 'Key 3bcb2e4b7e9028c24a0363d988ac482fcc28a0e6 not found in /da5_fast/All.sha1c/commit_59.tch'}

  7%|███████████████                                                                                                                                                                                          | 350/4682 [05:57<1:13:36,  1.02s/it]

Got Errors {'3c2a38f290a3a285aec087716200f62fc29d47c8': 'Key 3c2a38f290a3a285aec087716200f62fc29d47c8 not found in /da5_fast/All.sha1c/commit_60.tch'}

  8%|███████████████                                                                                                                                                                                          | 352/4682 [05:59<1:13:33,  1.02s/it]

Got Errors {'3cb7bad64151b84e7df196b57d6ec9c0f904eadd': 'Key 3cb7bad64151b84e7df196b57d6ec9c0f904eadd not found in /da5_fast/All.sha1c/commit_60.tch'}

  8%|███████████████▊                                                                                                                                                                                         | 368/4682 [06:16<1:13:17,  1.02s/it]

Got Errors {'468a282258309241af81beb7fc40b4a1832610f7': 'Key 468a282258309241af81beb7fc40b4a1832610f7 not found in /da5_fast/All.sha1c/commit_70.tch'}

  8%|███████████████▉                                                                                                                                                                                         | 370/4682 [06:18<1:13:13,  1.02s/it]

Got Errors {'4806261f918ced1d0ba9ebc4f2bd0b57e4e0b69c': 'Key 4806261f918ced1d0ba9ebc4f2bd0b57e4e0b69c not found in /da5_fast/All.sha1c/commit_72.tch'}

  8%|████████████████▎                                                                                                                                                                                        | 380/4682 [06:28<1:13:22,  1.02s/it]

Got Errors {'4d650f8da0411bb824bb0893a54ac034f8430ee1': 'Key 4d650f8da0411bb824bb0893a54ac034f8430ee1 not found in /da5_fast/All.sha1c/commit_77.tch'}

  9%|█████████████████▍                                                                                                                                                                                       | 406/4682 [06:55<1:12:44,  1.02s/it]

Got Errors {'5e2b62c7c5f58cffe65853f3bbe3368da32318d1': 'Key 5e2b62c7c5f58cffe65853f3bbe3368da32318d1 not found in /da5_fast/All.sha1c/commit_94.tch'}

  9%|█████████████████▊                                                                                                                                                                                       | 416/4682 [07:05<1:12:33,  1.02s/it]

Got Errors {'649646de07b5e3782815105c2ec3164e1ba8c5cf': 'Key 649646de07b5e3782815105c2ec3164e1ba8c5cf not found in /da5_fast/All.sha1c/commit_100.tch'}

  9%|██████████████████▋                                                                                                                                                                                      | 436/4682 [07:25<1:12:42,  1.03s/it]

Got Errors {'6f7bb41d2e3db7e49d6316e33e21317dbdbf1c4f': 'Key 6f7bb41d2e3db7e49d6316e33e21317dbdbf1c4f not found in /da5_fast/All.sha1c/commit_111.tch'}

  9%|██████████████████▊                                                                                                                                                                                      | 438/4682 [07:27<1:12:22,  1.02s/it]

Got Errors {'701d0b83470d72d72d3f17726c5d7781a354d222': 'Key 701d0b83470d72d72d3f17726c5d7781a354d222 not found in /da5_fast/All.sha1c/commit_112.tch'}

 10%|███████████████████▎                                                                                                                                                                                     | 450/4682 [07:40<1:12:38,  1.03s/it]

Got Errors {'774d5260db654feda2b01d11af4787fe915536b3': 'Key 774d5260db654feda2b01d11af4787fe915536b3 not found in /da5_fast/All.sha1c/commit_119.tch'}

 10%|███████████████████▌                                                                                                                                                                                     | 456/4682 [07:46<1:11:53,  1.02s/it]

Got Errors {'7be227db8fc8398dfe2f330d0f6b62016597de98': 'Key 7be227db8fc8398dfe2f330d0f6b62016597de98 not found in /da5_fast/All.sha1c/commit_123.tch'}

 10%|███████████████████▊                                                                                                                                                                                     | 462/4682 [07:52<1:11:48,  1.02s/it]

Got Errors {'7f058a870283d0486f7f6ecf14c57afc13628f72': 'Key 7f058a870283d0486f7f6ecf14c57afc13628f72 not found in /da5_fast/All.sha1c/commit_127.tch'}

 10%|████████████████████▌                                                                                                                                                                                    | 478/4682 [08:08<1:11:48,  1.02s/it]

Got Errors {'87366e0eabfb0c103c2fc337106108c10c10213d': 'Key 87366e0eabfb0c103c2fc337106108c10c10213d not found in /da5_fast/All.sha1c/commit_7.tch'}

 10%|████████████████████▊                                                                                                                                                                                    | 484/4682 [08:14<1:11:21,  1.02s/it]

Got Errors {'8ad07d3bcb9e159f21a3be4dcdc1643d5145958c': 'Key 8ad07d3bcb9e159f21a3be4dcdc1643d5145958c not found in /da5_fast/All.sha1c/commit_10.tch'}

 10%|████████████████████▊                                                                                                                                                                                    | 485/4682 [08:15<1:11:19,  1.02s/it]

Got Errors {'8af4130618b2553593c4cce7acb3bc14f1155568': 'Key 8af4130618b2553593c4cce7acb3bc14f1155568 not found in /da5_fast/All.sha1c/commit_10.tch'}

 10%|████████████████████▊                                                                                                                                                                                    | 486/4682 [08:16<1:11:18,  1.02s/it]

Got Errors {'8bfbda50c56f86931f6c1437f6e5d4d633bfdf2d': 'Key 8bfbda50c56f86931f6c1437f6e5d4d633bfdf2d not found in /da5_fast/All.sha1c/commit_11.tch'}

 11%|█████████████████████▎                                                                                                                                                                                   | 497/4682 [08:28<1:11:23,  1.02s/it]

Got Errors {'9242f215b616c5113a4d8ee424a07091d1c808e7': 'Key 9242f215b616c5113a4d8ee424a07091d1c808e7 not found in /da5_fast/All.sha1c/commit_18.tch'}

 11%|█████████████████████▍                                                                                                                                                                                   | 498/4682 [08:29<1:11:19,  1.02s/it]

Got Errors {'92cbc2e238d5f510b22d2a7495edc48503369b57': 'Key 92cbc2e238d5f510b22d2a7495edc48503369b57 not found in /da5_fast/All.sha1c/commit_18.tch'}

 11%|█████████████████████▌                                                                                                                                                                                   | 502/4682 [08:33<1:11:03,  1.02s/it]

Got Errors {'95302e614b67a27b7b942ff835f889e305ca52d9': 'Key 95302e614b67a27b7b942ff835f889e305ca52d9 not found in /da5_fast/All.sha1c/commit_21.tch'}

 11%|█████████████████████▊                                                                                                                                                                                   | 509/4682 [08:40<1:12:03,  1.04s/it]

Got Errors {'99107d6da4690633e844b7dba4f00d40b03a2498': 'Key 99107d6da4690633e844b7dba4f00d40b03a2498 not found in /da5_fast/All.sha1c/commit_25.tch'}

 11%|██████████████████████▉                                                                                                                                                                                  | 534/4682 [09:06<1:11:04,  1.03s/it]

Got Errors {'a798ada35e151e024046e7c764b2d77c405254d1': 'Key a798ada35e151e024046e7c764b2d77c405254d1 not found in /da5_fast/All.sha1c/commit_39.tch'}

 12%|███████████████████████▏                                                                                                                                                                                 | 539/4682 [09:11<1:10:28,  1.02s/it]

Got Errors {'ab776be9e1b2a51c6661c742acd6cf502be9c190': 'Key ab776be9e1b2a51c6661c742acd6cf502be9c190 not found in /da5_fast/All.sha1c/commit_43.tch'}

 12%|███████████████████████▍                                                                                                                                                                                 | 546/4682 [09:18<1:10:22,  1.02s/it]

Got Errors {'aecca50da81fb2d3a1452ff77c861c05a54f33f3': 'Key aecca50da81fb2d3a1452ff77c861c05a54f33f3 not found in /da5_fast/All.sha1c/commit_46.tch'}

 12%|███████████████████████▊                                                                                                                                                                                 | 556/4682 [09:28<1:10:10,  1.02s/it]

Got Errors {'b49dde46fa128df5350d5de76040d3c8dc8a10e5': 'Key b49dde46fa128df5350d5de76040d3c8dc8a10e5 not found in /da5_fast/All.sha1c/commit_52.tch'}

 13%|█████████████████████████▌                                                                                                                                                                               | 594/4682 [10:07<1:09:28,  1.02s/it]

Got Errors {'ca64ee84726689bc6c03c7e65b6692888f0fecbc': 'Key ca64ee84726689bc6c03c7e65b6692888f0fecbc not found in /da5_fast/All.sha1c/commit_74.tch'}

 13%|█████████████████████████▊                                                                                                                                                                               | 601/4682 [10:14<1:09:29,  1.02s/it]

Got Errors {'ceaa8556827e091adacb6c109c80508b851c5360': 'Key ceaa8556827e091adacb6c109c80508b851c5360 not found in /da5_fast/All.sha1c/commit_78.tch'}

 13%|██████████████████████████▉                                                                                                                                                                              | 628/4682 [10:42<1:08:59,  1.02s/it]

Got Errors {'ddc556473ee08eeaf9cdccb34579c8788787ac7f': 'Key ddc556473ee08eeaf9cdccb34579c8788787ac7f not found in /da5_fast/All.sha1c/commit_93.tch'}

 13%|███████████████████████████                                                                                                                                                                              | 631/4682 [10:45<1:09:02,  1.02s/it]

Got Errors {'dffdae1800db0765a83432e2095f6aba0580be30': 'Key dffdae1800db0765a83432e2095f6aba0580be30 not found in /da5_fast/All.sha1c/commit_95.tch'}

 14%|███████████████████████████▏                                                                                                                                                                             | 633/4682 [10:47<1:09:03,  1.02s/it]

Got Errors {'e14fb25bd68721e526c5f1b69764a111ac96c25a': 'Key e14fb25bd68721e526c5f1b69764a111ac96c25a not found in /da5_fast/All.sha1c/commit_97.tch'}

 15%|█████████████████████████████▏                                                                                                                                                                           | 680/4682 [11:35<1:07:58,  1.02s/it]

Got Errors {'fe13269aa0d7bac771c1d0245bd14a74b0226077': 'Key fe13269aa0d7bac771c1d0245bd14a74b0226077 not found in /da5_fast/All.sha1c/commit_126.tch'}

 30%|███████████████████████████████████████████████████████████▊                                                                                                                                              | 1385/4682 [23:36<58:19,  1.06s/it]

Got Errors {'090769edb46915902a8a1d5862e1cf8c955f3865': 'Key 090769edb46915902a8a1d5862e1cf8c955f3865 not found in /da5_fast/All.sha1c/commit_9.tch'}

 31%|██████████████████████████████████████████████████████████████▉                                                                                                                                           | 1459/4682 [24:54<56:15,  1.05s/it]

Got Errors {'2adfeba7817e4c76960ce7b376c3e28e5d3e00e6': 'Key 2adfeba7817e4c76960ce7b376c3e28e5d3e00e6 not found in /da5_fast/All.sha1c/commit_42.tch'}

 33%|██████████████████████████████████████████████████████████████████▏                                                                                                                                       | 1534/4682 [26:13<55:13,  1.05s/it]

Got Errors {'49a113a3c7d4595cd6195f296e138e1f210502ec': 'Key 49a113a3c7d4595cd6195f296e138e1f210502ec not found in /da5_fast/All.sha1c/commit_73.tch'}

 33%|██████████████████████████████████████████████████████████████████▊                                                                                                                                       | 1549/4682 [26:29<54:51,  1.05s/it]

Got Errors {'502025d1f59ca8ae68505ec3b1273695b8265ee4': 'Key 502025d1f59ca8ae68505ec3b1273695b8265ee4 not found in /da5_fast/All.sha1c/commit_80.tch'}

 35%|█████████████████████████████████████████████████████████████████████▉                                                                                                                                    | 1622/4682 [27:45<53:27,  1.05s/it]

Got Errors {'70384a17f67469006a266aa1581fcde2314e84cf': 'Key 70384a17f67469006a266aa1581fcde2314e84cf not found in /da5_fast/All.sha1c/commit_112.tch'}

 35%|███████████████████████████████████████████████████████████████████████                                                                                                                                   | 1647/4682 [28:12<53:22,  1.06s/it]

Got Errors {'79f55bef661250fdc989d9914d418919702768b6': 'Key 79f55bef661250fdc989d9914d418919702768b6 not found in /da5_fast/All.sha1c/commit_121.tch', '7a8130725d1610e3f418ecb10eaae35ea1b37c70': 'Key 7a8130725d1610e3f418ecb10eaae35ea1b37c70 not found in /da5_fast/All.sha1c/commit_122.tch'}

 36%|████████████████████████████████████████████████████████████████████████▉                                                                                                                                 | 1690/4682 [28:57<52:08,  1.05s/it]

Got Errors {'8bcb4e58c63ad76c6078c303c11971fd1a073f08': 'Key 8bcb4e58c63ad76c6078c303c11971fd1a073f08 not found in /da5_fast/All.sha1c/commit_11.tch'}

 37%|█████████████████████████████████████████████████████████████████████████▉                                                                                                                                | 1715/4682 [29:23<51:42,  1.05s/it]

Got Errors {'96270f9b50e3e18a58cbfed3009f74f67593e5ed': 'Key 96270f9b50e3e18a58cbfed3009f74f67593e5ed not found in /da5_fast/All.sha1c/commit_22.tch'}

 38%|████████████████████████████████████████████████████████████████████████████▍                                                                                                                             | 1772/4682 [30:22<50:44,  1.05s/it]

Got Errors {'af2d7b047c287087a694e4389d8105e179a61907': 'Key af2d7b047c287087a694e4389d8105e179a61907 not found in /da5_fast/All.sha1c/commit_47.tch'}

 38%|████████████████████████████████████████████████████████████████████████████▋                                                                                                                             | 1778/4682 [30:29<50:35,  1.05s/it]

Got Errors {'b13aa53e2bc27e34a359fa807a9244bfef046913': 'Key b13aa53e2bc27e34a359fa807a9244bfef046913 not found in /da5_fast/All.sha1c/commit_49.tch'}

 38%|████████████████████████████████████████████████████████████████████████████▉                                                                                                                             | 1782/4682 [30:33<50:32,  1.05s/it]

Got Errors {'b2d7b0f054eae76b3882d7ee1191716624d6f0e3': 'Key b2d7b0f054eae76b3882d7ee1191716624d6f0e3 not found in /da5_fast/All.sha1c/commit_50.tch'}

 39%|██████████████████████████████████████████████████████████████████████████████                                                                                                                            | 1809/4682 [31:01<50:08,  1.05s/it]

Got Errors {'be35a5debc6b32e7753f72ab63a29659079b8527': 'Key be35a5debc6b32e7753f72ab63a29659079b8527 not found in /da5_fast/All.sha1c/commit_62.tch'}

 42%|████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                     | 1959/4682 [33:37<46:58,  1.03s/it]

Got Errors {'f9e05fed39c841e93bd7012cdcbb330d1e7d8a04': 'Key f9e05fed39c841e93bd7012cdcbb330d1e7d8a04 not found in /da5_fast/All.sha1c/commit_121.tch'}

 42%|████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                     | 1961/4682 [33:39<46:59,  1.04s/it]

Got Errors {'fa7c1f5ebb48715da5053439ce9af3398015230a': 'Key fa7c1f5ebb48715da5053439ce9af3398015230a not found in /da5_fast/All.sha1c/commit_122.tch'}

 42%|█████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                    | 1988/4682 [34:07<46:24,  1.03s/it]

Got Errors {'018264bb27d739d10973fa9734014bd27fa79f36': 'Key 018264bb27d739d10973fa9734014bd27fa79f36 not found in /da5_fast/All.sha1c/commit_1.tch'}

 43%|███████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                  | 2033/4682 [34:54<45:28,  1.03s/it]

Got Errors {'05ab3b810ac79f4a5a6d023b774970244e660006': 'Key 05ab3b810ac79f4a5a6d023b774970244e660006 not found in /da5_fast/All.sha1c/commit_5.tch'}

 44%|███████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                  | 2037/4682 [34:58<45:24,  1.03s/it]

Got Errors {'0612ec646a4788c4352579ee15577a7715f97019': 'Key 0612ec646a4788c4352579ee15577a7715f97019 not found in /da5_fast/All.sha1c/commit_6.tch'}

 45%|██████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                               | 2102/4682 [36:05<44:27,  1.03s/it]

Got Errors {'0c7a88c84fcc6ad151fba11ce9d2444241baa4a5': 'Key 0c7a88c84fcc6ad151fba11ce9d2444241baa4a5 not found in /da5_fast/All.sha1c/commit_12.tch'}

 45%|██████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                               | 2107/4682 [36:10<44:20,  1.03s/it]

Got Errors {'0d09479fe9b04f89972c1222949a02b39617c60f': 'Key 0d09479fe9b04f89972c1222949a02b39617c60f not found in /da5_fast/All.sha1c/commit_13.tch'}

 45%|███████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                              | 2130/4682 [36:34<44:08,  1.04s/it]

Got Errors {'0f194e64d2fed9704d1afaa2835d2a3d020a7ab3': 'Key 0f194e64d2fed9704d1afaa2835d2a3d020a7ab3 not found in /da5_fast/All.sha1c/commit_15.tch'}

 50%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                    | 2359/4682 [40:30<39:56,  1.03s/it]

Got Errors {'26017cf4d9450e80a8c0b32781420b09224c4607': 'Key 26017cf4d9450e80a8c0b32781420b09224c4607 not found in /da5_fast/All.sha1c/commit_38.tch'}

 54%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                             | 2516/4682 [43:13<37:12,  1.03s/it]

Got Errors {'35696f84f6ce6a3f0e2a0ce18afc11a852329b07': 'Key 35696f84f6ce6a3f0e2a0ce18afc11a852329b07 not found in /da5_fast/All.sha1c/commit_53.tch'}

 54%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                            | 2530/4682 [43:27<37:05,  1.03s/it]

Got Errors {'369cfc0c9a5b94980db2e731d016eaa8bd5485b2': 'Key 369cfc0c9a5b94980db2e731d016eaa8bd5485b2 not found in /da5_fast/All.sha1c/commit_54.tch'}

 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                           | 2557/4682 [43:55<36:35,  1.03s/it]

Got Errors {'38e5aa14daa33d4664fd3e35b236c0a01eb06526': 'Key 38e5aa14daa33d4664fd3e35b236c0a01eb06526 not found in /da5_fast/All.sha1c/commit_56.tch'}

 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                           | 2570/4682 [44:09<36:18,  1.03s/it]

Got Errors {'3a355690baf7c5df1617c962712bd44c819554b0': 'Key 3a355690baf7c5df1617c962712bd44c819554b0 not found in /da5_fast/All.sha1c/commit_58.tch'}

 55%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                           | 2574/4682 [44:13<36:18,  1.03s/it]

Got Errors {'3aa42e01c748e36eeb76957b261202000d21baa3': 'Key 3aa42e01c748e36eeb76957b261202000d21baa3 not found in /da5_fast/All.sha1c/commit_58.tch'}

 56%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                        | 2626/4682 [45:07<35:41,  1.04s/it]

Got Errors {'401dd1ba1c96d4e36fe927e2ec835590465ab2aa': 'Key 401dd1ba1c96d4e36fe927e2ec835590465ab2aa not found in /da5_fast/All.sha1c/commit_64.tch'}

 57%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                      | 2671/4682 [45:53<34:49,  1.04s/it]

Got Errors {'4421440f97adeace887f582714e2edb6c750378d': 'Key 4421440f97adeace887f582714e2edb6c750378d not found in /da5_fast/All.sha1c/commit_68.tch'}

 58%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                     | 2709/4682 [46:33<33:55,  1.03s/it]

Got Errors {'479f85a2f7614f4acadfb63e1a39367757c8a8c3': 'Key 479f85a2f7614f4acadfb63e1a39367757c8a8c3 not found in /da5_fast/All.sha1c/commit_71.tch'}

 58%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                    | 2718/4682 [46:42<33:48,  1.03s/it]

Got Errors {'4870b1b368c69b9f79222acaa2ce518adb0d7609': 'Key 4870b1b368c69b9f79222acaa2ce518adb0d7609 not found in /da5_fast/All.sha1c/commit_72.tch'}

 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                               | 2838/4682 [48:46<31:45,  1.03s/it]

Got Errors {'53c890bd8e3f50632a7126887b79fa52862ba15a': 'Key 53c890bd8e3f50632a7126887b79fa52862ba15a not found in /da5_fast/All.sha1c/commit_83.tch'}

 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                           | 2935/4682 [50:26<30:08,  1.04s/it]

Got Errors {'5d1d323200a707488c379a5f744809568fa78ca3': 'Key 5d1d323200a707488c379a5f744809568fa78ca3 not found in /da5_fast/All.sha1c/commit_93.tch'}

 64%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                        | 3007/4682 [51:41<28:50,  1.03s/it]

Got Errors {'64228f9f561b8231c2ab885695a7c78f605ea6d5': 'Key 64228f9f561b8231c2ab885695a7c78f605ea6d5 not found in /da5_fast/All.sha1c/commit_100.tch'}

 65%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                      | 3062/4682 [52:37<27:52,  1.03s/it]

Got Errors {'69606179bad8fa8f178771e7de77d6e644047e37': 'Key 69606179bad8fa8f178771e7de77d6e644047e37 not found in /da5_fast/All.sha1c/commit_105.tch'}

 67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                  | 3135/4682 [53:53<26:39,  1.03s/it]

Got Errors {'7011f062fe16c28a45b8076ac40c6b3df4ff543c': 'Key 7011f062fe16c28a45b8076ac40c6b3df4ff543c not found in /da5_fast/All.sha1c/commit_112.tch'}

 68%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                               | 3207/4682 [55:07<25:24,  1.03s/it]

Got Errors {'770d059b2d6dc0c122f2a6f294bc52662453699f': 'Key 770d059b2d6dc0c122f2a6f294bc52662453699f not found in /da5_fast/All.sha1c/commit_119.tch'}

 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                               | 3212/4682 [55:12<25:16,  1.03s/it]

Got Errors {'77770e0292c4a7561bc67c17890658e7eb623069': 'Key 77770e0292c4a7561bc67c17890658e7eb623069 not found in /da5_fast/All.sha1c/commit_119.tch'}

 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                        | 3377/4682 [58:03<22:27,  1.03s/it]

Got Errors {'87454ab60e686697fa8c119cc3b238380cd3d951': 'Key 87454ab60e686697fa8c119cc3b238380cd3d951 not found in /da5_fast/All.sha1c/commit_7.tch'}

 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                        | 3383/4682 [58:09<22:18,  1.03s/it]

Got Errors {'87d8064da7e00e7da3c735fe3cba282c11e60f15': 'Key 87d8064da7e00e7da3c735fe3cba282c11e60f15 not found in /da5_fast/All.sha1c/commit_7.tch'}

 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                               | 3581/4682 [1:01:33<18:53,  1.03s/it]

Got Errors {'9ae5b5e4dac720bdeb7884363c61bdd1d70d182b': 'Key 9ae5b5e4dac720bdeb7884363c61bdd1d70d182b not found in /da5_fast/All.sha1c/commit_26.tch'}

 77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                              | 3589/4682 [1:01:41<18:47,  1.03s/it]

Got Errors {'9b98c319e7634d1b4980b5b7506838d2510bdd91': 'Key 9b98c319e7634d1b4980b5b7506838d2510bdd91 not found in /da5_fast/All.sha1c/commit_27.tch'}

 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                           | 3671/4682 [1:03:06<17:24,  1.03s/it]

Got Errors {'a38d6177abfc9a809804bab81c71450cf0d27e68': 'Key a38d6177abfc9a809804bab81c71450cf0d27e68 not found in /da5_fast/All.sha1c/commit_35.tch'}

 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                        | 3730/4682 [1:04:07<16:21,  1.03s/it]

Got Errors {'a916343c3578a039c478cd6cd6f5f1748bc3fbb1': 'Key a916343c3578a039c478cd6cd6f5f1748bc3fbb1 not found in /da5_fast/All.sha1c/commit_41.tch'}

 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                       | 3755/4682 [1:04:33<15:56,  1.03s/it]

Got Errors {'ab521e2526907aefa7bd4d95c4068fa7de7a3185': 'Key ab521e2526907aefa7bd4d95c4068fa7de7a3185 not found in /da5_fast/All.sha1c/commit_43.tch'}

 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                      | 3777/4682 [1:04:56<15:33,  1.03s/it]

Got Errors {'ad48720da2698ecf7cd7d749aae6c44fcb592450': 'Key ad48720da2698ecf7cd7d749aae6c44fcb592450 not found in /da5_fast/All.sha1c/commit_45.tch'}

 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                     | 3812/4682 [1:05:32<14:59,  1.03s/it]

Got Errors {'b08dfc86d02c9747c8ed3755a92f860c1ec76e53': 'Key b08dfc86d02c9747c8ed3755a92f860c1ec76e53 not found in /da5_fast/All.sha1c/commit_48.tch'}

 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                 | 3904/4682 [1:07:07<13:22,  1.03s/it]

Got Errors {'b93986b7bc76576d6c248d188346e4bf5ce97825': 'Key b93986b7bc76576d6c248d188346e4bf5ce97825 not found in /da5_fast/All.sha1c/commit_57.tch'}

 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                               | 3958/4682 [1:08:02<12:26,  1.03s/it]

Got Errors {'be36c6d119891e0cf15868053fbfb24701dcad54': 'Key be36c6d119891e0cf15868053fbfb24701dcad54 not found in /da5_fast/All.sha1c/commit_62.tch'}

 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                      | 4154/4682 [1:11:24<09:05,  1.03s/it]

Got Errors {'d146e32f033341d10011ac7da4de0308d7fca122': 'Key d146e32f033341d10011ac7da4de0308d7fca122 not found in /da5_fast/All.sha1c/commit_81.tch'}

 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                     | 4190/4682 [1:12:02<08:27,  1.03s/it]

Got Errors {'d4786baf479fd289784dabf4126e2443ea6e8914': 'Key d4786baf479fd289784dabf4126e2443ea6e8914 not found in /da5_fast/All.sha1c/commit_84.tch'}

 90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                     | 4192/4682 [1:12:04<08:25,  1.03s/it]

Got Errors {'d49cad8157c5e550c0114f21488d33cf6fdd21d6': 'Key d49cad8157c5e550c0114f21488d33cf6fdd21d6 not found in /da5_fast/All.sha1c/commit_84.tch'}

 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊            | 4397/4682 [1:15:35<04:54,  1.03s/it]

Got Errors {'e7813b36c1c6b6cad2333099a48388e60e2a36a3': 'Key e7813b36c1c6b6cad2333099a48388e60e2a36a3 not found in /da5_fast/All.sha1c/commit_103.tch'}

 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 4456/4682 [1:16:36<03:53,  1.03s/it]

Got Errors {'ed637d482422748d24f4ac61c2c1dc2e5d439f68': 'Key ed637d482422748d24f4ac61c2c1dc2e5d439f68 not found in /da5_fast/All.sha1c/commit_109.tch'}

 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍         | 4458/4682 [1:16:38<03:50,  1.03s/it]

Got Errors {'ed924c79f42e2b207863e89d7fbd442f4e304792': 'Key ed924c79f42e2b207863e89d7fbd442f4e304792 not found in /da5_fast/All.sha1c/commit_109.tch'}

 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉       | 4518/4682 [1:17:40<02:48,  1.03s/it]

Got Errors {'f337b5b3ad6152201373807f164f9252dc65ded7': 'Key f337b5b3ad6152201373807f164f9252dc65ded7 not found in /da5_fast/All.sha1c/commit_115.tch'}

 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 4524/4682 [1:17:46<02:42,  1.03s/it]

Got Errors {'f3d853ee7e172d2320bdb7099c54b3f4557a625a': 'Key f3d853ee7e172d2320bdb7099c54b3f4557a625a not found in /da5_fast/All.sha1c/commit_115.tch'}

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏   | 4594/4682 [1:18:58<01:30,  1.03s/it]

Got Errors {'fa4bb9c7e8f1771276df76967c0aaae2713bf985': 'Key fa4bb9c7e8f1771276df76967c0aaae2713bf985 not found in /da5_fast/All.sha1c/commit_122.tch'}

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4682/4682 [1:20:29<00:00,  1.03s/it]

,commit,tree,parent,author,author_time,author_tz,committer,committer_time,committer_tz,message,sha1,project
0,00011bd91daf73b71f1278d52a35424b176a8807,cfa8d062707922f663311f5a9c1f541364611d15,[d92d14eb861bba2095258f49f054402303ea8d18],Marc-Alexandre Côté <marc.cote.19@gmail.com>,1663382841,-0400,Marc-Alexandre Côté <marc.cote.19@gmail.com>,1663382922,-0400,Rename main branch and references to it.\n,00011bd91daf73b71f1278d52a35424b176a8807,microsoft_textworld
1,00640623ba2c422d75e3d23eed92d24876037ade,d22a175b1f4b62384f79558fe2e113af6519d68d,[0593109adec574e5a72c7d3cd7f61ea816006767],Marc-Alexandre Côté <marc.cote.19@gmail.com>,1702342627,-0500,GitHub <noreply@github.com>,1702342627,-0500,Update prerelease.yml,00640623ba2c422d75e3d23eed92d24876037ade,microsoft_textworld

In [6]:
print("Retrieved commits:", len(commit_data))
print("Total SHA-1s:", len(df))
print("Missing commits:", len(df) - len(commit_data))

Retrieved commits: 46711
Total SHA-1s: 46816
Missing commits: 105

In [7]:
# what does the first record looks like?
# commit  parents
v = commit_data[0]
# commit tree, [parent{s}], [author, unixtime, tz ], [ committer, unixtime, tz ], Commit_message ]
print(v)

{'commit': '00011bd91daf73b71f1278d52a35424b176a8807', 'tree': 'cfa8d062707922f663311f5a9c1f541364611d15', 'parent': ['d92d14eb861bba2095258f49f054402303ea8d18'], 'author': 'Marc-Alexandre Côté <marc.cote.19@gmail.com>', 'author_time': 1663382841, 'author_tz': '-0400', 'committer': 'Marc-Alexandre Côté <marc.cote.19@gmail.com>', 'committer_time': 1663382922, 'committer_tz': '-0400', 'message': 'Rename main branch and references to it.\n'}

In [8]:
# Keep each commit associated with its correct project.
dfinf = df_commit_data[
    ['project', 'commit', 'author', 'author_time', 'message']
].copy()

dfinf.columns = [
    'project_wocid',
    'commit_sha1',
    'author',
    'time',
    'commit message'
]

dfinf.head(1)

,project_wocid,commit_sha1,author,time,commit message
0,microsoft_textworld,00011bd91daf73b71f1278d52a35424b176a8807,Marc-Alexandre Côté <marc.cote.19@gmail.com>,1663382841,Rename main branch and references to it.\n

In [9]:
# Check that the CSV has the required columns and content.
dfinf.head(1)

,project_wocid,commit_sha1,author,time,commit message
0,microsoft_textworld,00011bd91daf73b71f1278d52a35424b176a8807,Marc-Alexandre Côté <marc.cote.19@gmail.com>,1663382841,Rename main branch and references to it.\n

In [10]:
# Save one semicolon-separated CSV containing all retrieved projects.
yournetid = 'smazunda'
dfinf.to_csv(yournetid + '_project_summary.csv', index=False, sep=';')

# Make sure you check in to your fork not just the notebook but also the csv files!!!

# Don't forget to add requested data from github and this notebook
### For each of the 10 projects go to their github repo and get the number of stars, number of forks, and the last commit date
### Report (in your notebook) the number of commits, the number of authors, and max and min time for each project based on WoC commits and also add the info you obtained from github

In [11]:
# Report WoC commit counts, unique authors, and timestamp range for each project.
df_commit_data['author_time'] = pd.to_numeric(df_commit_data['author_time'], errors='coerce')
woc_stats = df_commit_data.groupby('project').agg(
    ncommits=('commit', 'nunique'),
    nauthors=('author', 'nunique'),
    min_time=('author_time', 'min'),
    max_time=('author_time', 'max')
).reset_index()

woc_stats['min_time'] = pd.to_datetime(woc_stats['min_time'], unit='s', utc=True)
woc_stats['max_time'] = pd.to_datetime(woc_stats['max_time'], unit='s', utc=True)
display(woc_stats)

,project,ncommits,nauthors,min_time,max_time
0,cgentemann_cloud_science,574,16,2019-04-01 21:40:04+00:00,2024-11-07 17:39:46+00:00
1,exascience_macau,4273,17,2016-01-05 11:36:25+00:00,2025-03-10 13:32:05+00:00
2,gauzias_slam,596,27,2019-04-30 08:27:53+00:00,2024-11-29 10:34:15+00:00
3,ivanlh20_multem,420,20,2014-08-29 14:53:07+00:00,2025-09-14 08:44:06+00:00
4,keras-team_autokeras,5202,273,2017-11-19 23:18:21+00:00,2025-01-14 08:45:02+00:00
5,microsoft_textworld,927,44,2018-06-26 18:00:56+00:00,2025-01-23 17:19:27+00:00
6,microsoft_unilm,1578,161,2019-07-23 04:15:29+00:00,2025-09-13 14:02:31+00:00
7,mitgcm_mitgcm,26776,206,1998-04-22 19:15:31+00:00,2025-11-08 17:31:14+00:00
8,mrgiovanni_modelsgenesis,274,15,2019-07-24 19:07:20+00:00,2025-06-22 18:38:35+00:00
9,slundberg_shap,6091,588,2016-11-22 21:44:11+00:00,2025-11-12 02:59:12+00:00

In [13]:
# Retrieve GitHub stars, forks, and latest commit date for each repository.
import requests
import time

github_rows = []
for repo in projects:
    response = requests.get(f'https://api.github.com/repos/{repo}', timeout=30)
    response.raise_for_status()
    repo_data = response.json()

    commit_response = requests.get(
        f'https://api.github.com/repos/{repo}/commits',
        params={'per_page': 1},
        timeout=30
    )
    commit_response.raise_for_status()
    commit_list = commit_response.json()

    github_rows.append({
        'repository': repo,
        'stars': repo_data['stargazers_count'],
        'forks': repo_data['forks_count'],
        'last_commit_date': (
            commit_list[0]['commit']['committer']['date']
            if commit_list else 'N/A'
        )
    })
    time.sleep(1)

github_stats = pd.DataFrame(github_rows)
display(github_stats)

                 repository  stars  forks      last_commit_date
0       microsoft/TextWorld   1447    206  2026-09-28T13:36:06Z
1           microsoft/unilm  22225   2706  2026-09-21T03:26:59Z
2          ExaScience/macau     69     12  2026-02-10T07:25:29Z
3      keras-team/autokeras   9333   1388  2025-11-25T02:26:35Z
4  cgentemann/cloud_science     26     17  2024-11-07T17:39:46Z
5              gauzias/slam      1      0  2024-11-29T10:31:33Z
6           Ivanlh20/multem     80     29  2025-07-03T14:04:49Z
7            slundberg/shap  25784   3755  2026-09-28T18:57:07Z
8             MITgcm/MITgcm    407    296  2026-09-06T15:41:07Z
9  MrGiovanni/ModelsGenesis    794    142  2026-08-25T17:16:33Z